exports.report = function(test){
var fonts = {
	Roboto: {
		normal: './node_modules/pdfmake/fonts/Time Roman.ttf',
		bold: './node_modules/pdfmake/fonts/Time Roman Bold.ttf',
		italics: './node_modules/pdfmake/fonts/Time Roman Italic.ttf',
		bolditalics: './node_modules/pdfmake/fonts/Time Roman Italic.ttf'
	}
};

var PdfPrinter = require('pdfmake/src/printer');
var printer = new PdfPrinter(fonts);
var fs = require('fs');

var docDefinition = {
	pageSize: 'LETTER',
  	pageMargins: [ 72, 72, 72, 72 ],
  	footer: function(page,pages){  return {text :'© Copyright 2016, DIC, University Of Delhi',alignment:'center'} },
	background: function(page) {
        if (page !== 1) {
            return [         
            		{text :'DUCIC 24X7 WS 1.0',alignment: 'center' },
                	{text :'                      ' + page, alignment : 'right'},	             
            ]
        }},
	content: [
		{
			text: ['Auto-generated Feasibility Study Report\n',
					{text:'of\n',italics :true},
					'24x7 Water Supply System implementation\n',
					'[village name,location]\n'
			],
			style: 'header',
			alignment: 'center',
			
		},
		{
			text: [
				'\n\n\n\n\n[DD.MM.YYYY]\n Delhi\n\n\n\n\n',
				'Generated By\n',
				'[---text---]\n\n'
				],
			style: 'header',
			bold: false,
			alignment :'center'
		},
		{
			text: [
				{text :'Initiative By\n', bold : true},
				'Design Innovation Centre \n',
				'CIC, University Of Delhi\n',
				'Dream Building,North Campus\n',
				'New Delhi - 110007\n',
				{text :'http://dudic.io', italics:true}
				],
			style: 'header',
			alignment:'center',
			bold: false
		},
		{
			text: ['______________________________________________________\n'],
			style: 'header',
			alignment:'center',
			pageBreak : 'after'
			
		},
		{
			text: [
					{text : '\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nDisclaimer\n\n',fontSize : 12 ,bold : true, alignment : 'center'},
					{text :'This document is intended solely for information purposes and should not to be construed, under any circumstances, by implication or otherwise, as an official tender document. The information mentioned here is obtained from sources considered to be reliable, but is in no way guaranteed. The institution is not liable for any loss incurred in the course of execution and operation of the project. This is a software generated and unreviewed draft of the project plan for a general overview. The final report will be generated after a month long detailed review by experts, agencies who specialize in planning of such projects.',alignment: 'justify',fontSize : 10}
					],
			pageBreak : 'after'
		},
		{
			text: ['Key Points\n\n\n\n',
			],
			style: 'header',
			alignment: 'center',	
		},
		{
			text: [
				'Village name  : '+ test +'\n\n',
				'Initiated By : tmptmp \n\n',
				'Project Code : tmptmp\n\n',
				'Queried on : tmptmp\n\n',
				'Generated on : 00/00/0000\n\n',
				'Generated using : --------\n\n',
				'Population data : 000000\n\n',
				'Water source : tmptmp\n\n',
				'Water Demand  : 00000\n\n',
				'Maintenance cost per annum :00000\n\n',
				'Total cost of the project :000000'
				],
			style: 'header',
			alignment:'center',
			italics : true,
			pageBreak : 'after'
		},
		{
			alignment: 'justify',
			columns:[
				{
					width : 500,
					text :'Summary \n\n',
					fontSize : 22,
					bold: true,
					
				},
				{
					width : 100,
					text :''
				},
				]
		},
		{
			alignment: 'justify',
			columns:[
				{
					width : 500,
					text : 'Lorem ipsum dolor sit amet, pede nulla, nam praesent odio. Eu placerat, in pellentesque varius. Ante sodales rutrum, eu aliquet dictum, turpis rutrum, id auctor. Pharetra in adipiscing semper quisque lectus sit, morbi metus proin erat, tortor diam semper pellentesque elit, nunc leo dignissim vitae ipsum vivamus. Nec elementum, pellentesque orci nulla lectus et. Semper ultricies. Accumsan tincidunt nulla aliquam in nam, sociis duis adipiscing. Quis lorem, orci fames tortor. Consequat dolor nec purus, odio morbi vitae, taciti at feugiat libero. Tincidunt placerat tempor odio interdum. adipiscing semper quisque lectus sit adipiscing semper quisque lectus sit adipiscing semper quisque lectus sit, morbi metus proin erat, tortor diam semper pellentesque elit, nunc leo dignissim vitae ipsum vivamus. Nec elementum, pellentesque orci nulla adipiscing semper quisque lectus sit adipiscing semper quisque lectus sit adipiscing semper quisque',
					fontSize : 19				
				},
				],
			pageBreak : 'after'
		},
		{
			alignment :'center',
			text : 'Contents\n\n',
			fontSize : 22,
			bold: true,
		},
		{	
			alignment :'justify',
			text :'Key Points....................................................................... 2 \nSummary ........................................................................ 3\n Section I: Project Planning Area ................................... 2\n Section II: Proposed Project.......................................... 3\n Section III: Tariff Model.................................................. 4\n Section IV: Appendices ................................................. 5\n Appendix A: Figures ....................................................... 5 \nAppendix B: Engineering guide .................................... 5\n Appendix C : Assumptions ............................................ 6 \nSection V : Data Reference ........................................ 7\n',
			pageBreak : 'after',
			fontSize : 19
		},
		
		{
			alignment:'center',
			text : "Section I : Project Planning Area\n\n\n",
			fontSize : 25,
			bold :true
		},
		{
			alignment:'justify',
			text : "A. Location Data\n\n",
			fontSize : 16,

		},
		{
			alignment:'justify',
			text : "The location where this project will be implemented is [complete address obtained from google API geocode]\n\n\n",
		},
		{
			alignment:'justify',
			text : "B. Population Data\n\n",
			fontSize : 16,
		},
		{
						style: 'tableExample',
						table: {
								body: [
										['Year', 'Population'],
										['2011', '####'],
										['2001', '####'],
										['1991', '####'],
										['1981', '####']
								]
						}
		},
		{
			italic : true,
			text : "**data of last four decades obtained from census of India website(mention source)\n\n\n"
		},
		{
			alignment:'justify',
			text : "C. Area Details\n\n",
			
			fontSize : 16,
		},
		{
			alignment:'justify',
			text : "Total number of institutions (school, hospitals, offices, factories) in the village [ ]\n\nTotal number of livestock in the village [ ]\n\nTotal number of households in the village: [ ]\n\nRange (Min, Max) or Average income of the households in the village: [ ]\n\n**information obtained from user through online survey\n\n\n"
		},
		{
			alignment:'justify',
			text : "D. Water Source\n\n",
			fontSize : 16,
		},
		{
			alignment:'justify',
			text : "Option 1: [River source, location, distance from the village]\n\nOption 2: [Groundwater, type of level of ground water] \n\nTotal Water demand [assumption refer Appendix C]",
			pageBreak : 'after'
		},
		{
			alignment:'center',
			text : "Section II : Proposal Project \n\n\n",
			fontSize : 25,
			bold :true
		},
		{
			alignment:'justify',
			text : "A. Water network(tabular data)\n\n",
			bold : true,
			fontSize : 16,
		},
		{
						style: 'tableExample',
						table: {
								body: [
										['Nodes', 'Distance' , 'Type of Pipeline' , 'Qty'],
										['#', '##' , '###' , '####']
								]
						}
		},
		{
			alignment:'justify',
			text : "**Node Network\n\n",
		},
		{
						style: 'tableExample',
						table: {
								body: [
										['Material', 'Units' , 'Price' , 'Total cost'],
										['#', '##' , '###' , '####']
								]
						}
		},

		{
			alignment:'justify',
			text : "**BoQ\n\n\n",
		},
		{
			alignment:'justify',
			text : "B. Reservoir, filtration tank description\n\n",
			bold : true,
			fontSize : 16,
		},
		{
			alignment:'justify',
			text : "Reservoir,filtration tank or any other infrastructure data [what all can we mention in a table here + source of data] Lorem ipsum dolor sit amet, pede nulla, nam praesent odio. Eu placerat, in pellentesque varius. Ante sodales rutrum, eu aliquet dictum, turpis rutrum, id auctor. Pharetra in adipiscing semper quisque lectus sit, morbi metus proin erat, tortor diam semper pellentesque elit, nunc leo dignissim vitae ipsum vivamus. Nec elementum, pellentesque orci nulla Lorem ipsum dolor sit amet, pede nulla, nam praesent odio. Eu placerat, in pellentesque varius. Ante sodales rutrum, eu aliquet dictum, turpis rutrum, id auctor. Pharetra in adipiscing semper quisque lectus sit, morbi metus proin erat, tortor diam semper pellentesque elit, nunc leo dignissim vitae ipsum vivamus. Nec elementum, pellentesque orci nulla\n\n\n",
		},
		{
			alignment:'justify',
			text : "C. Project cost details (fixed cost + maintenance cost)\n\n",
			bold : true,
			fontSize :16
		},

		{
			alignment:'justify',
			text : "a. infrastructure Cost\nb. Maintenance Cost [includes repair, electricity charges and labor costs]\nc. Operation costs [labor costs, meter costs, new installation etc]\n\n",
		},
		{
						style: 'tableExample',
						table: {
								body: [
										['Cost heads', 'Details'],
										['Recurring Cost', 'Maintenance Cost'],
										['Non-recurring Cost' , 'Infrastructure Cost'],
										['Total' , '#']								
						]
						},
						pageBreak : 'after'
		},
		{
			alignment:'center',
			text : "Section III : Tariff Model \n\n\n",
			fontSize : 25,
			bold :true
		},
		{
			alignment:'justify',
			text : "Model 1 : (for areas with more lower income groups)\n\n",
		},
		{
						style: 'tableExample',
						table: {
								widths: [200, 200],
								body: [
										['Slabs', 'Tariff'],
										['', ''],
										['', ''],
										['', ''],
										['', '']
								]
						}
		},
		{
			alignment:'justify',
			text : "Model 2 : (for areas with balanced income groups)\n\n",
		},
		{
						style: 'tableExample',
						table: {
								widths: [200,200],
								body: [
										['Slabs', 'Tariff'],
										['', ''],
										['', ''],
										['', ''],
										['', '']
								]
						}
		},
		{
			alignment:'justify',
			text : "Model 3 : (for areas with upper income groups)\n\n",
		},
		{
						style: 'tableExample',
						table: {
								widths: [200, 200],
								body: [
										['Slabs', 'Tariff'],
										['', ''],
										['', ''],
										['', ''],
										['', '']
								]
						},
						pageBreak : 'after'
		},
		{
			alignment:'center',
			text : "Section IV : Appendices \n\n\n",
			fontSize : 25,
			bold :true
		},
		{
			alignment:'center',
			text : "Appendix A : Figures \n\n",
			fontSize : 22,
			bold :true
		},
		{
			alignment:'justify',
			text : "a.  Satellite images\n\n",
			image : ''
		},
		{
			alignment:'justify',
			text : "b.  Network images\n\n\n",
			image : ''
		},
		{
			alignment:'center',
			text : "Appendix B : Engineering guide \n\n",
			fontSize : 22,
			bold :true
		},
		{
			alignment:'justify',
			text : "a.  Filtration Palnt description\n\nLorem ipsum dolor sit amet, pede nulla, nam praesent odio. Eu placerat, in pellentesque varius. Ante sodales rutrum, eu aliquet dictum, turpis rutrum, id auctor. Pharetra in adipiscing semper quisque lectus sit, morbi metus proin erat, tortor diam semper pellentesque elit, nunc leo dignissim vitae ipsum vivamus. Nec elementum, pellentesque orci nulla\n",
		},
		{
			alignment:'justify',
			text : "b.  Supply details\n\nLorem ipsum dolor sit amet, pede nulla, nam praesent odio. Eu placerat, in pellentesque varius. Ante sodales rutrum, eu aliquet dictum, turpis rutrum, id auctor. Pharetra in adipiscing semper quisque lectus sit, morbi metus proin erat, tortor diam semper pellentesque elit, nunc leo dignissim vitae ipsum vivamus. Nec elementum, pellentesque orci nulla\n",
		},
		{
			alignment:'justify',
			text : "c. Reservoir details\n\nLorem ipsum dolor sit amet, pede nulla, nam praesent odio. Eu placerat, in pellentesque varius. Ante sodales rutrum, eu aliquet dictum, turpis rutrum, id auctor. Pharetra in adipiscing semper quisque lectus sit, morbi metus proin erat, tortor diam semper pellentesque elit, nunc leo dignissim vitae ipsum vivamus. Nec elementum, pellentesque orci nulla\n",
		},
		{
			alignment:'justify',
			text : "d.  Tools used\n\nLorem ipsum dolor sit amet, pede nulla, nam praesent odio. Eu placerat, in pellentesque varius. Ante sodales rutrum, eu aliquet dictum, turpis rutrum, id auctor. Pharetra in adipiscing semper quisque lectus sit, morbi metus proin erat, tortor diam semper pellentesque elit, nunc leo dignissim vitae ipsum vivamus. Nec elementum\n\n",
		},
			{
			alignment:'center',
			text : "Appendix C : Assumptions \n\n",
			fontSize : 22,
			bold :true
		},
		{
			alignment:'justify',
			text : "-> River or groundwater source would suffice the water demand of the village.\n-> The map of the village specifies the administrative boundary of the village\n-> Availability of river or groundwater as water source\n\n\n",
			pageBreak : 'after'
		},
		{
			alignment:'center',
			text : "Section V : Data Reference \n\n",
			fontSize : 22,
			bold :true
		},
		{
			alignment : 'justify',
			ol: [
            'Google API',
            'subitem 2',
            'subitem 3 - Lorem ipsum dolor sit amet, consectetur adipisicing elit. Malit profecta versatur nomine ocurreret multavit',
            'subitem 3 - Lorem ipsum dolor sit amet, consectetur adipisicing elit. Malit profecta versatur nomine ocurreret multavit',
            'subitem 3 - Lorem ipsum dolor sit amet, consectetur adipisicing elit. Malit profecta versatur nomine ocurreret multavit',]
		}
		],
	styles: {
		header: {
			fontSize: 18,
			bold: true,
			alignment: 'justify'
		},
		tableExample: {
			margin: [0, 5, 0, 15]
		}
	},
};

var pdfDoc = printer.createPdfKitDocument(docDefinition);
pdfDoc.pipe(fs.createWriteStream('tmp/basics.pdf'));
pdfDoc.end();


};